package com.iwtg.ipaymonitor.datalayer.model;
// Generated 24/03/2018 02:37:22 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Audit generated by hbm2java
 */
public class Audit  implements java.io.Serializable {


     private Integer id;
     private String nroTransaccion;
     private String accion;
     private Date fecha;
     private String estado;

    public Audit() {
    }

    public Audit(String nroTransaccion, String accion, Date fecha, String estado) {
       this.nroTransaccion = nroTransaccion;
       this.accion = accion;
       this.fecha = fecha;
       this.estado = estado;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNroTransaccion() {
        return this.nroTransaccion;
    }
    
    public void setNroTransaccion(String nroTransaccion) {
        this.nroTransaccion = nroTransaccion;
    }
    public String getAccion() {
        return this.accion;
    }
    
    public void setAccion(String accion) {
        this.accion = accion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


