package com.iwtg.ipaymonitor.datalayer.model;
// Generated 24/03/2018 02:37:22 AM by Hibernate Tools 4.3.1



/**
 * Canal generated by hbm2java
 */
public class Canal  implements java.io.Serializable {


     private String idCanal;
     private String nombre;

    public Canal() {
    }

    public Canal(String idCanal, String nombre) {
       this.idCanal = idCanal;
       this.nombre = nombre;
    }
   
    public String getIdCanal() {
        return this.idCanal;
    }
    
    public void setIdCanal(String idCanal) {
        this.idCanal = idCanal;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


