package com.iwtg.ipaymonitor.datalayer.model;
// Generated 24/03/2018 02:37:22 AM by Hibernate Tools 4.3.1



/**
 * CanalHasUsuarios generated by hbm2java
 */
public class CanalHasUsuarios  implements java.io.Serializable {


     private CanalHasUsuariosId id;

    public CanalHasUsuarios() {
    }

    public CanalHasUsuarios(CanalHasUsuariosId id) {
       this.id = id;
    }
   
    public CanalHasUsuariosId getId() {
        return this.id;
    }
    
    public void setId(CanalHasUsuariosId id) {
        this.id = id;
    }




}


