package com.iwtg.ipaymonitor.datalayer.model;
// Generated 24/03/2018 02:37:22 AM by Hibernate Tools 4.3.1



/**
 * CierreLote generated by hbm2java
 */
public class CierreLote  implements java.io.Serializable {


     private String codigoRes;
     private String tarjeta;
     private String autorizacion;
     private String codcomercio;
     private String lote;

    public CierreLote() {
    }

    public CierreLote(String codigoRes, String tarjeta, String autorizacion, String codcomercio, String lote) {
       this.codigoRes = codigoRes;
       this.tarjeta = tarjeta;
       this.autorizacion = autorizacion;
       this.codcomercio = codcomercio;
       this.lote = lote;
    }
   
    public String getCodigoRes() {
        return this.codigoRes;
    }
    
    public void setCodigoRes(String codigoRes) {
        this.codigoRes = codigoRes;
    }
    public String getTarjeta() {
        return this.tarjeta;
    }
    
    public void setTarjeta(String tarjeta) {
        this.tarjeta = tarjeta;
    }
    public String getAutorizacion() {
        return this.autorizacion;
    }
    
    public void setAutorizacion(String autorizacion) {
        this.autorizacion = autorizacion;
    }
    public String getCodcomercio() {
        return this.codcomercio;
    }
    
    public void setCodcomercio(String codcomercio) {
        this.codcomercio = codcomercio;
    }
    public String getLote() {
        return this.lote;
    }
    
    public void setLote(String lote) {
        this.lote = lote;
    }




}


