package com.iwtg.ipaymonitor.datalayer.model;
// Generated 24/03/2018 02:37:22 AM by Hibernate Tools 4.3.1



/**
 * Lotes generated by hbm2java
 */
public class Lotes  implements java.io.Serializable {


     private int lote;

    public Lotes() {
    }

    public Lotes(int lote) {
       this.lote = lote;
    }
   
    public int getLote() {
        return this.lote;
    }
    
    public void setLote(int lote) {
        this.lote = lote;
    }




}


