package com.iwtg.ipaymonitor.datalayer.model;
// Generated 24/03/2018 02:37:22 AM by Hibernate Tools 4.3.1



/**
 * Mediopago generated by hbm2java
 */
public class Mediopago  implements java.io.Serializable {


     private String idMpago;
     private String nombre;

    public Mediopago() {
    }

    public Mediopago(String idMpago, String nombre) {
       this.idMpago = idMpago;
       this.nombre = nombre;
    }
   
    public String getIdMpago() {
        return this.idMpago;
    }
    
    public void setIdMpago(String idMpago) {
        this.idMpago = idMpago;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


