package com.iwtg.ipaymonitor.datalayer.model;
// Generated 24/03/2018 02:37:22 AM by Hibernate Tools 4.3.1



/**
 * MediopagoHasUsuarios generated by hbm2java
 */
public class MediopagoHasUsuarios  implements java.io.Serializable {


     private MediopagoHasUsuariosId id;

    public MediopagoHasUsuarios() {
    }

    public MediopagoHasUsuarios(MediopagoHasUsuariosId id) {
       this.id = id;
    }
   
    public MediopagoHasUsuariosId getId() {
        return this.id;
    }
    
    public void setId(MediopagoHasUsuariosId id) {
        this.id = id;
    }




}


