package com.iwtg.ipaymonitor.datalayer.model;
// Generated 24/03/2018 02:37:22 AM by Hibernate Tools 4.3.1



/**
 * MediopagoHasUsuariosId generated by hbm2java
 */
public class MediopagoHasUsuariosId  implements java.io.Serializable {


     private int idUsuario;
     private String idMpago;

    public MediopagoHasUsuariosId() {
    }

    public MediopagoHasUsuariosId(int idUsuario, String idMpago) {
       this.idUsuario = idUsuario;
       this.idMpago = idMpago;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getIdMpago() {
        return this.idMpago;
    }
    
    public void setIdMpago(String idMpago) {
        this.idMpago = idMpago;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MediopagoHasUsuariosId) ) return false;
		 MediopagoHasUsuariosId castOther = ( MediopagoHasUsuariosId ) other; 
         
		 return (this.getIdUsuario()==castOther.getIdUsuario())
 && ( (this.getIdMpago()==castOther.getIdMpago()) || ( this.getIdMpago()!=null && castOther.getIdMpago()!=null && this.getIdMpago().equals(castOther.getIdMpago()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdUsuario();
         result = 37 * result + ( getIdMpago() == null ? 0 : this.getIdMpago().hashCode() );
         return result;
   }   


}


