package com.iwtg.ipaymonitor.datalayer.model;
// Generated 24/03/2018 02:37:22 AM by Hibernate Tools 4.3.1



/**
 * Notifications generated by hbm2java
 */
public class Notifications  implements java.io.Serializable {


     private String codReserva;

    public Notifications() {
    }

    public Notifications(String codReserva) {
       this.codReserva = codReserva;
    }
   
    public String getCodReserva() {
        return this.codReserva;
    }
    
    public void setCodReserva(String codReserva) {
        this.codReserva = codReserva;
    }




}


