package com.iwtg.ipaymonitor.datalayer.model;
// Generated 24/03/2018 02:37:22 AM by Hibernate Tools 4.3.1



/**
 * PaisHasUsuarios generated by hbm2java
 */
public class PaisHasUsuarios  implements java.io.Serializable {


     private PaisHasUsuariosId id;

    public PaisHasUsuarios() {
    }

    public PaisHasUsuarios(PaisHasUsuariosId id) {
       this.id = id;
    }
   
    public PaisHasUsuariosId getId() {
        return this.id;
    }
    
    public void setId(PaisHasUsuariosId id) {
        this.id = id;
    }




}


