package com.iwtg.ipaymonitor.datalayer.model;
// Generated 24/03/2018 02:37:22 AM by Hibernate Tools 4.3.1



/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private String idPais;
     private String nombre;

    public Pais() {
    }

    public Pais(String idPais, String nombre) {
       this.idPais = idPais;
       this.nombre = nombre;
    }
   
    public String getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(String idPais) {
        this.idPais = idPais;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


