package com.iwtg.ipaymonitor.datalayer.model;
// Generated 24/03/2018 02:37:22 AM by Hibernate Tools 4.3.1



/**
 * PaisHasUsuariosId generated by hbm2java
 */
public class PaisHasUsuariosId  implements java.io.Serializable {


     private int idUsuario;
     private String idPais;

    public PaisHasUsuariosId() {
    }

    public PaisHasUsuariosId(int idUsuario, String idPais) {
       this.idUsuario = idUsuario;
       this.idPais = idPais;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(String idPais) {
        this.idPais = idPais;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PaisHasUsuariosId) ) return false;
		 PaisHasUsuariosId castOther = ( PaisHasUsuariosId ) other; 
         
		 return (this.getIdUsuario()==castOther.getIdUsuario())
 && ( (this.getIdPais()==castOther.getIdPais()) || ( this.getIdPais()!=null && castOther.getIdPais()!=null && this.getIdPais().equals(castOther.getIdPais()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdUsuario();
         result = 37 * result + ( getIdPais() == null ? 0 : this.getIdPais().hashCode() );
         return result;
   }   


}


