package com.iwtg.ipaymonitor.datalayer.model;
// Generated 24/03/2018 02:37:22 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Transaction generated by hbm2java
 */
public class Transaction  implements java.io.Serializable {


     private String codigoRes;
     private String canal;
     private String pais;
     private String medioPago;
     private String moneda;
     private String estado;
     private Date fecha;
     private String nombre;
     private String apellido;
     private String mail;
     private String documento;
     private String monto;
     private String codCard;
     private boolean notify;
     private boolean notifyMyWay;

    public Transaction() {
    }

	
    public Transaction(String codigoRes, String canal, String pais, String medioPago, String moneda, Date fecha, String nombre, String apellido, String mail, String documento, String monto, String codCard, boolean notify, boolean notifyMyWay) {
        this.codigoRes = codigoRes;
        this.canal = canal;
        this.pais = pais;
        this.medioPago = medioPago;
        this.moneda = moneda;
        this.fecha = fecha;
        this.nombre = nombre;
        this.apellido = apellido;
        this.mail = mail;
        this.documento = documento;
        this.monto = monto;
        this.codCard = codCard;
        this.notify = notify;
        this.notifyMyWay = notifyMyWay;
    }
    public Transaction(String codigoRes, String canal, String pais, String medioPago, String moneda, String estado, Date fecha, String nombre, String apellido, String mail, String documento, String monto, String codCard, boolean notify, boolean notifyMyWay) {
       this.codigoRes = codigoRes;
       this.canal = canal;
       this.pais = pais;
       this.medioPago = medioPago;
       this.moneda = moneda;
       this.estado = estado;
       this.fecha = fecha;
       this.nombre = nombre;
       this.apellido = apellido;
       this.mail = mail;
       this.documento = documento;
       this.monto = monto;
       this.codCard = codCard;
       this.notify = notify;
       this.notifyMyWay = notifyMyWay;
    }
   
    public String getCodigoRes() {
        return this.codigoRes;
    }
    
    public void setCodigoRes(String codigoRes) {
        this.codigoRes = codigoRes;
    }
    public String getCanal() {
        return this.canal;
    }
    
    public void setCanal(String canal) {
        this.canal = canal;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getMedioPago() {
        return this.medioPago;
    }
    
    public void setMedioPago(String medioPago) {
        this.medioPago = medioPago;
    }
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }
    public String getMonto() {
        return this.monto;
    }
    
    public void setMonto(String monto) {
        this.monto = monto;
    }
    public String getCodCard() {
        return this.codCard;
    }
    
    public void setCodCard(String codCard) {
        this.codCard = codCard;
    }
    public boolean isNotify() {
        return this.notify;
    }
    
    public void setNotify(boolean notify) {
        this.notify = notify;
    }
    public boolean isNotifyMyWay() {
        return this.notifyMyWay;
    }
    
    public void setNotifyMyWay(boolean notifyMyWay) {
        this.notifyMyWay = notifyMyWay;
    }




}


